FROM centos:7
LABEL maintainer="Tim Dudgeon<tdudgeon@informaticsmatters.com>"

RUN yum update -y &&\
 yum install -y --setopt=tsflags=nodocs --setopt=override_install_langs=en_US.utf8\
 docker-client\
 java-1.8.0-openjdk-headless &&\
 yum clean -y all &&\
 rm -rf /var/cache/yum 
 
ENV JAVA_HOME /usr/lib/jvm/jre-openjdk/

RUN useradd -u 567 -g 0 -m nextflow &&\
 groupadd docker &&\
 usermod -aG docker nextflow

USER 567
WORKDIR /home/nextflow

RUN curl -fsSL get.nextflow.io | bash && chmod 755 nextflow
USER root
RUN mv /home/nextflow/nextflow /usr/local/bin
USER 567

